# Language and env

language: node_js
node_js: 'node'

# What is built

branches:
  only:
  - master

# Travis Lifecycle

before_install:
  - npm i -g npm@5.7.1 # this should be deleted once 5.7.X is out of "pre-release"

install:
  - npm ci

script:
  - npm run build-demo
  - npm test

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./tools/deploy.sh
  on:
    branch: master

# Other configs

git:
  depth: 10
