language: node_js
node_js: '6'

cache:
  directories:
  - node_modules

before_script:
- npm run build-demo

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./tools/deploy.sh
  on:
    branch: master
